#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export RUST_LOG=trace 
export DART_LOG=verbose
export DC=$DC
export RC=$RC
export VERBOSE=$VERBOSE

PROG="messages"

$DIR/core/valgrind $PROG
