use proc_macro2::TokenStream;
use syn::Ident;

/// Types like `*const X` and `*mut X` are aliased in order to avoid confusing and
/// non-deterministic names being generated by bindgen when they're used as generic types, for
/// instance in `RidVec<T>`.
/// For example `*const Item` is aliased to `Pointer_Item` which then results in
/// `RidVec_Pointer_Item` instead of something like `RidVec______Item`.
#[derive(Debug, Clone)]
pub struct PointerTypeAlias {
    pub alias: Ident,
    pub typedef: TokenStream,
    pub type_name: String,
    pub needs_free: bool,
}
