name: wasm_example 
version: 0.0.0
publish: none
environment:
  sdk: '>=2.14.0 <=3.0.0'

ffigen:
  output: 'lib/generated/ffigen_binding.dart'
  headers:
    entry-points:
      - 'lib/generated/bindings.h'

dependencies: 
  ffi: ^1.0.0
  ffigen: ^2.2.4
  wasm_interop:
    path: '../../../../wasm/wasm.dart/wasm_interop'
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: ^1.17.8
