name: wasm_example 
version: 0.0.0
publish: none
environment:
  sdk: '>=2.12.0 <=3.0.0'

ffigen:
  output: 'lib/generated/ffigen_binding.dart'
  headers:
    entry-points:
      - 'lib/generated/bindings.h'

dependencies: 
  ffi: ^1.0.0
  ffigen: ^2.2.4
  wasm: 
    path: ../../../../dart-libs/wasm
