name: wasm_example 
version: 0.0.0
publish: none
environment:
  sdk: '>=2.13.0 <=3.0.0'

ffigen:
  output: 'lib/generated/ffigen_binding.dart'
  headers:
    entry-points:
      - 'lib/generated/bindings.h'

wasmjsgen:
  comments: false
  output: 'lib/generated/ffigen_binding.dart'
  headers:
    entry-points:
      - 'lib/generated/bindings.h'

dependencies: 
  ffi: ^1.0.0
  ffigen: ^2.2.4
  wasm_interop: ^2.0.0
  universal_io: ^2.0.4
  wasmjsgen:
    path: ../../../../wasmjsgen/

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: ^1.17.8
