#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

(cd $DIR/.. && cargo run rid_build)
(cd $DIR/.. && pub run wasmjsgen --verbose severe)
cp $DIR/../lib/generated/rid_api.sav.dart $DIR/../lib/generated/rid_api.dart 
