name: Build+Test

on:
  push:
    branches: [ master, chore/gh-ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    # ffigen depends on Dart v2.14+  
    - uses: dart-lang/setup-dart@v1.2
      with:
          sdk: 2.14.0-115.0.dev

    - uses: actions/checkout@master

    - name: Build and Run Tests
      run: make test 
