name: Build+Test

on:
  push:
    branches: [ master, chore/gh-ci ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        sdk: [2.14.0-115.0.dev] # ffigen depends on Dart v2.14+  

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}

    # ffigen depends on an llvm installation
    - name: Install libclang-10-dev
      run: sudo apt-get install libclang-10-dev

    - uses: dart-lang/setup-dart@v1.2
      with:
          sdk: ${{ matrix.sdk }} 

    - uses: actions/checkout@master

    - name: Build and Run Tests
      run: make test 
